<?php

function sign_up_msg($userid)//remain
{
	$message="Welcome to Blyss Fintech, you have been successfully registered with UserId: $userid\nPassword: blyss@12\nT-Pin: 1234\n\nFeel free to call us @ 9896677625\nBLYSSPAY.IN";
	return $message;
}

function create_forgot_msg($pass_word)//done
{
	$message="Dear Retailer,\n\nYour credentials to use the BLYSS Portal\n\nPassword : $pass_word\n\nDo not share with anyone.\n\nFeel free to call us @ 9896677625";
	return $message;
}

function create_forgot_msg_not($dtm)//remain
{
	$message="ALERT: Your request to initiate forgot password declined at $dtm.\n\nIf not requested by you, please change password & tpin immediately.";
	return $message;
}

function reset_password_msg()//remain
{
	$message="Dear Retailer,\n\nAs requested by you, your login password had been reset as 'blyss@12'\n\nPlease change password immediately after login.\n\nTeam BLYSS\n9896677625";
	return $message;
}

function reset_tpin_msg()//remain
{
	$message="Dear Retailer,\n\nAs requested by you, your T-Pin had been reset as '1234'\n\nPlease change T-Pin immediately after login.\n\nTeam BLYSS\n9896677625";
	return $message;
}

function support_ticket_reply_msg()//remain
{
	$message="Dear Retailer you have received a reply on Support Ticket Generated by you. Kindly check & revert on solution provided.\n\nFeel free to call us @ 9896677625";
	return $message;
}

function create_payone_wallet_request_msg($request_id,$user_id,$user_name,$amt,$bank,$datetime_time)//done
{
	$message="Wallet Request Id:$request_id\n\nat $datetime_time\n\nby $user_id ($user_name)\n\nRs. $amt in $bank";
	return $message;
}

function create_payone_wallet_request_msg_reply($dtm,$user_name,$amt,$status)//done
{
	if($status==2)
	$status="Accepted";
	else if($status==3)
	$status="Rejected";
	
	if($status==1)
	$message="";
	else
	$message="Dear $user_name,\n\nYour Wallet Request for Rs. $amt had been $status by wallet team at $dtm.\n\nTeam BLYSS\n9896677625";
	return $message;
}
/*
function create_mentor_wallet_request_msg($user_id,$amt,$datetime_time)
{
	$message="Wallet request received of Rs. $amt from PAYONE $user_id at $datetime_time";
	return $message;
}

function create_mentor_wallet_request_msg_reply($request_status,$amt,$datetime_time)
{
	if($request_status==2)
	$request_status="completed successfully";
	else if($request_status==3)
	$request_status="rejected";
	
	if($request_status==1)
	$message="";
	else
	$message="Wallet request updated of Rs. $amt for PAYONE is $request_status at $datetime_time";
	return $message;
}
*/
function create_registration_msg($id,$type,$name)//done
{
	$message="Welcome to Blyss Fintech, you have been successfully registered with UserId: $id\nPassword: blyss@12\nT-Pin: 1234\n\nFeel free to call us @ 9896677625\nBLYSSPAY.IN";
	return $message;
}

function zsms2($mobile,$message)
{
}

function zsms($mobile,$message)
{
	$online_url=$_SERVER['HTTP_HOST'];
	if($online_url=="payoneonline.com")
	{
		$user="kuldeep60008";
		$pass="990067";
		$sender="PAYONE";
		$phone=$mobile;
		$text=$message;
		$priority="ndnd";
		$stype="normal";
		$url="http://bhashsms.com/api/sendmsg.php";
		
		$data = array(
		'user' => $user, 
		'pass' => $pass, 
		'sender' => $sender, 
		'phone' => $phone, 
		'text' => $text, 
		'priority' => $priority, 
		'stype' => $stype);
		
		$handle = curl_init($url);
		curl_setopt($handle, CURLOPT_POST, true);
		curl_setopt($handle, CURLOPT_POSTFIELDS, $data);
		ob_start();
		$buffer = curl_exec($handle);
		ob_end_clean();
		curl_close($handle);
	}
	else
	{
	    zsms_new_bin($mobile,$message);
	}
}

function zsms_new_bin($mobile,$message)
{
	$online_url=$_SERVER['HTTP_HOST'];
	if($online_url=="blysspay.com" || $online_url=="blysspay.in")
	{
	    $api_key = '55B27EE010F9BB';
		$contacts = $mobile;
		$from = 'BLYSSS';
		$sms_text = urlencode($message);

		$ch = curl_init();
		curl_setopt($ch,CURLOPT_URL, "http://bulksms.smsbin.com/app/smsapi/index.php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, "key=".$api_key."&campaign=0&routeid=45&type=text&contacts=".$contacts."&senderid=".$from."&msg=".$sms_text);
		$response = curl_exec($ch);
		curl_close($ch);
	}
}
?>