<?php
function txn_add_benificiary($userid, $cno, $cname, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method)
{
	$err="";
	$txn_status=1;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	//$client_otp_pending_refund=admin_otp_refund();
	//$admin_otp_pending_refund=$client_otp_pending_refund;
	
	$deduction_retailer=4;//show_user_av_rate($source);
	$deduction_client=show_client_av_rate($source);
	$deduction_admin=show_admin_av_rate($source);
	$charged=$charges=0;
	
	if($balance_retailer<$deduction_retailer && $userid!=$testing2)
		$err="Your Balance is low for transaction.";
	//if($balance_client-$balance_client_dummy+$client_otp_pending_refund<$deduction_client)
		//$txn_status=4;
	//if($balance_admin+$admin_otp_pending_refund<$deduction_admin)
		//$txn_status=4;
	if($err=="")
	{
		$brid=0;
		$amount=0;
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		$duplicate_txn=0;
		if($duplicate_txn!=0)
		{
			$err="<b>Repeated Transaction</b>:: You already had performed same transaction with same amount to this beneficiary today. If you still want to continue, kindly change transaction amount.";
		}
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			$ded_ret=$deduction_retailer;
			$remain_ret=$balance_retailer-$ded_ret;
			$ded_client=$deduction_client;
			$remain_client=$balance_client-$ded_client;
			$ded_admin=$deduction_admin;
			$remain_admin=$balance_admin-$ded_admin;
			
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret')";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("9896677625","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$qry2="";			
			$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
			$order_id=generate_mt_client_txn_child($qry2);
			if($order_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("9896677625","Order No $order_id started on dated $datetime_datetime");
			}
			
			$qry3="";			
			$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$deduction_admin', '$charges', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
			$m_id=generate_mt_admin_txn($qry3);
			
			//update_mid_for_client
			$qry4="";
			$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
			mysql_query($qry4);
			
			//deduct_amount_for_retailer
			$qry5="";
			$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
			mysql_query($qry5);
			include_once('zf-WalletDistributed.php');
			update_user_balance($userid);
			
			//deduct_amount_for_client
			$qry6="";
			$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
			mysql_query($qry6);
			
			if($source==5)
			{
				//deduct_amount_for_admin
				$qry7="";
				$qry7="INSERT INTO $bankapi_parent_wallet.rt_ach_blyss(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
				mysql_query($qry7);
			}
			if($txn_status==1 || $txn_status==3)
			{
				if($source==5)
				{
					include_once('zf-TxnSource3DmtApi.php');
					$pan="";
					$aadhar="";
					$resulted_data=add_beneficiary_with_verify2($cno,$cname,$bacc,$bifsc,$pan,$aadhar,$m_id);
					$resulted_response=$resulted_data[6];
					$ASTransCode=$resulted_data[3];
					$ReferenceNumber=$resulted_data[4];
					$Status=$resulted_data[1];
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					if($resulted_data[5]!='' && $resulted_data[1]=='SUCCESS')
					{
						$txn_status=2;
						//update_benefid_tid_for_client_child
						$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';";
						mysql_query($qry8);
						
						//update_benefid_for_client_parent
						$qry9="update $bankapi_child_txn.txn_mt_parent set receiver_id='0' where txn_id='$txn_id';";
						mysql_query($qry9);
						
						//update_benefid_tid_for_admin
						$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response', receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', mmt_status='$txn_status', response_message='$Status' where mmt_id='$m_id';";
						mysql_query($qry10);
						
						//level wise margin for client
						
						$qry11="insert into $bankapi_child_txn.txn_mt_child_margin(order_id, txn_id, lvl_1_id, lvl_1_chg, lvl_12_id, lvl_12_chg, lcl_12_chgd) value ('$order_id', '$txn_id', '$main_admin', '3', '$userid', '$ded_ret', '$ded_ret')";
						mysql_query($qry11);
						
						//margin for admin
						
						$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$deduction_retailer', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
						mysql_query($qry12);
					}
					else if($resulted_data[5]=='' && $resulted_data[1]=='FAILED')
					{	//update_benefid_tid_for_admin
						$txn_status=-4;
						
						$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';";
						mysql_query($qry8);
						
						$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response', receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', mmt_status='$txn_status', response_message='$Status' where mmt_id='$m_id';";
						mysql_query($qry10);
					}
					else
					{	//update_benefid_tid_for_admin
						$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response' where mmt_id='$m_id';";
						mysql_query($qry10);
					}
					if($txn_status!=-4)
					{
						$client_earning=$ded_ret;
						$client_com_gen_qry="INSERT INTO $bankapi_child_txn.com_generated(order_id, tid, source, type, method, date_time, user_id, amount, charged, retailer_gst, retailer_com, admin_gst, admin_fee, lvl_1_id, lvl_1_com, lvl_1_tds, lvl_1_earn) value ('$order_id', '$ASTransCode', '$source', '$type', '$method', '$datetime', '$userid', '$ded_ret', '0', '0', '0', '0', '$ded_client', '$main_admin', '$client_earning', '0', '$client_earning')";
						mysql_query($client_com_gen_qry);
						
						$details="Earnings from order no: $order of user id: $uids at $datetime";
						$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$main_admin', '$source', '$type', '$method', '$datetime', '$details', '$client_earning', '$ded_client');";
						if($client_earning!=0)
						mysql_query($client_com_paid_qry);
					}
					return $resulted_data;
				}
			}
		}
	}
	return $err;//$err;
}
function txn_add_benificiary_verfied($userid, $cno, $cname, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method)
{
	$err="";
	$txn_status=1;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	//$client_otp_pending_refund=admin_otp_refund();
	//$admin_otp_pending_refund=$client_otp_pending_refund;
	
	$deduction_retailer=4;//show_user_av_rate($source);
	$deduction_client=0;//show_client_av_rate($source);
	$deduction_admin=0;
	$charged=$charges=0;
	
	if($balance_retailer<$deduction_retailer && $userid!=$testing2)
		$err="Your Balance is low for transaction.";
	//if($balance_client-$balance_client_dummy+$client_otp_pending_refund<$deduction_client)
		//$txn_status=41;
	//if($balance_admin+$admin_otp_pending_refund<$deduction_admin)
		//$txn_status=42;
	if($err=="")
	{
		$brid=0;
		$amount=0;
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		$duplicate_txn=0;
		if($duplicate_txn!=0)
		{
			$err="<b>Repeated Transaction</b>:: You already had performed same transaction with same amount to this beneficiary today. If you still want to continue, kindly change transaction amount.";
		}
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			$ded_ret=$deduction_retailer;
			$remain_ret=$balance_retailer-$ded_ret;
			$ded_client=$deduction_client;
			$remain_client=$balance_client-$ded_client;
			$ded_admin=$deduction_admin;
			$remain_admin=$balance_admin-$ded_admin;
			
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret')";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("9896677625","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$qry2="";			
			$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
			$order_id=generate_mt_client_txn_child($qry2);
			if($order_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("9896677625","Order No $order_id started on dated $datetime_datetime");
			}
			
			$qry3="";			
			$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$deduction_admin', '$charges', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
			$m_id=generate_mt_admin_txn($qry3);
			
			//update_mid_for_client
			$qry4="";
			$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
			mysql_query($qry4);
			
			//deduct_amount_for_retailer
			$qry5="";
			$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
			mysql_query($qry5);
			include_once('zf-WalletDistributed.php');
			update_user_balance($userid);
			
			//deduct_amount_for_client
			$qry6="";
			$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
			mysql_query($qry6);
			
			if($source==5)
			{
				//deduct_amount_for_admin
				$qry7="";
				$qry7="INSERT INTO $bankapi_parent_wallet.rt_ach_blyss(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
				mysql_query($qry7);
			}
			if($txn_status==1 || $txn_status==3)
			{
				if($source==5)
				{
					include_once('zf-TxnSource3DmtApi.php');
					$pan="";
					$aadhar="";
					//$resulted_data=add_beneficiary_with_verify2($cno,$cname,$bacc,$bifsc,$pan,$aadhar,$order_id);
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					//if($resulted_data[5]!="" && $resulted_data[1]=="SUCCESS")
					//{
						$txn_status=2;
						//$resulted_response=$resulted_data[6];
						//$ASTransCode=$resulted_data[3];
						//$ReferenceNumber=$resulted_data[4];
						//$Status=$resulted_data[1];
						
						//update_benefid_tid_for_client_child
						$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='0', tid='1234', bank_ref_no='4321', order_status='$txn_status' where order_id='$order_id';";
						mysql_query($qry8);
						
						//update_benefid_for_client_parent
						$qry9="update $bankapi_child_txn.txn_mt_parent set receiver_id='0' where txn_id='$txn_id';";
						mysql_query($qry9);
						
						//update_benefid_tid_for_admin
						$qry10="update $bankapi_parent_txn.txn_mt set response='1234-4321', receiver_id='0', tid='1234', bank_ref_no='4321', mmt_status='$txn_status', response_message='1234-4321' where mmt_id='$m_id';";
						mysql_query($qry10);
						
						//level wise margin for client
						
						$qry11="insert into $bankapi_child_txn.txn_mt_child_margin(order_id, txn_id, lvl_1_id, lvl_1_chg, lvl_12_id, lvl_12_chg, lcl_12_chgd) value ('$order_id', '$txn_id', '$main_admin', '3', '$userid', '$ded_ret', '$ded_ret')";
						mysql_query($qry11);
						
						//margin for admin
						
						$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$deduction_retailer', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
						mysql_query($qry12);
			
						$qry="insert into $bankapi_common.eko_receiver_verified(sender, bank, ifsc, receiver_acc_no, receiver_name, receiver_id_type, updated_on, source) value('$cno', '$bbname', '$bifsc', '$bacc', '$bname', '0', '$datetime_datetime', 3);";
						mysql_query($qry);
					//}
					//return $resulted_data;
				}
			}
		}
		if($err=="" && $txn_status!=-4)
		{
			$ASTransCode=1234;
			$client_earning=$ded_ret;
			$client_com_gen_qry="INSERT INTO $bankapi_child_txn.com_generated(order_id, tid, source, type, method, date_time, user_id, amount, charged, retailer_gst, retailer_com, admin_gst, admin_fee, lvl_1_id, lvl_1_com, lvl_1_tds, lvl_1_earn) value ('$order_id', '$ASTransCode', '$source', '$type', '$method', '$datetime', '$userid', '$ded_ret', '0', '0', '0', '0', '$ded_client', '$main_admin', '$client_earning', '0', '$client_earning')";
			mysql_query($client_com_gen_qry);
			
			$details="Earnings from order no: $order of user id: $uids at $datetime";
			$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$main_admin', '$source', '$type', '$method', '$datetime', '$details', '$client_earning', '$ded_client');";
			if($client_earning!=0)
			mysql_query($client_com_paid_qry);
		}
	}
	return $err;//$err;
}
function delete_beneficiary3_in_db($cno,$acc_no)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$qry="delete from $bankapi_common.eko_receiver_verified where sender='$cno' and receiver_acc_no='$acc_no' and source='3';";
	mysql_query($qry);
}
function is_verified($cno,$acc_no)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$verified=0;
	$qry="select * from $bankapi_common.eko_receiver_verified where receiver_acc_no='$acc_no' and source='1';";
	$result=mysql_query($qry);
	while($rs=mysql_fetch_array($result))
	{
		$verified=$rs['receiver_name'];
	}
	return $verified;
}
function show_verified_name_3($cno,$acc_no)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$verified="";
	$qry="select * from $bankapi_common.eko_receiver_verified where sender='$cno' and receiver_acc_no='$acc_no' and source='3';";
	$result=mysql_query($qry);
	while($rs=mysql_fetch_array($result))
	{
		$verified=$rs['receiver_name'];
	}
	return $verified;
}

function txn_fund_transfer3($userid, $cno, $cname, $brid, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method, $amount, $charges123, $charged123, $pan, $aadhar)//, $doctype, $docid, $areapincode, $geo
{
	$err="";
	$txn_status=1;
	if($charged123<$charges123)
		$charged123=$charges123;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	include_once('zf-Commission.php');
	$unpaid=show_unpaid_comm($userid);
	$unpaid=$unpaid*.75;
	
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	$client_otp_pending_refund=admin_otp_refund();
	$admin_otp_pending_refund=$client_otp_pending_refund;
	
	$deduction_retailer=show_user_mt_rate($userid, $source, $method, $amount);
	$deduction_client=show_client_mt_rate($source, $amount);
	$deduction_admin=show_admin_mt_rate($source, $method, $amount);
				
	if($charges123<$deduction_retailer)
		$charges123=$deduction_retailer;
	if($charged123<$charges123)
		$charged123=$charges123;
	$deduction_retailer=$charged123;
				
	$ded_ret=$amount+$deduction_retailer;
	$remain_ret=$balance_retailer-$ded_ret;
	$ded_client=$amount+$deduction_client;
	$remain_client=$balance_client-$ded_client;
	$ded_admin=$amount+$deduction_admin;
	$remain_admin=$balance_admin-$ded_admin;
	
	if(($balance_retailer+$unpaid)<($amount+$deduction_retailer))
		$err="Your Balance is low for transaction.";
	//if($balance_client-$balance_client_dummy+$client_otp_pending_refund<($amount+$deduction_client))
		//$txn_status=-1;
	if($balance_admin+$admin_otp_pending_refund<($amount+$deduction_admin))
		$txn_status=-2;
	if($err=="")
	{
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		/*if($userid==$testing2)
		$duplicate_txn=0;*/
		if($duplicate_txn!=0)
		$err="repeated";
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			
			$bbname2=$bbname;
			if(strlen($bbname2)==4)
			{
				$qry0="select * from $bankapi_common.eko_bank where bank_code='$bbname';";
				$res0=mysql_query($qry0);
				while($rs0=mysql_fetch_array($res0))
				{
					$bbname2=$rs0['bank_name'];
				}
			}
			$bbname2=$bbname;
			
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname2', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$amount', '$charges123', '$deduction_retailer', '$ded_ret', '$remain_ret');";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("9896677625","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$limit=5000;
			$amt=$amount;
			$done_charges=0;
			while($amt>=$limit)
			{
				sleep(1);
				$order_id=$m_id=$t_id=0;
				$amt=$amt-$limit;
			
				$balance_retailer=show_txn_user_balance($userid);
				$balance_client=show_txn_client_balance();
				$balance_admin=show_txn_admin_balance($source);
				
				$deduction_retailer=show_user_mt_rate($userid, $source, $method, $limit);
				$deduction_client=show_client_mt_rate($source, $limit);
				$deduction_admin=show_admin_mt_rate($source, $method, $limit);
				
				if($charges123!=$charged123)
				{
					$charges2=0;
					if($charges2<$deduction_retailer)
						$charges2=$deduction_retailer;
					$deduction_retailer=$limit*$charged123/$amount;
					if($charges2>$deduction_retailer)
						$deduction_retailer=$charges2;
				}
				else
				{
					$charges2=$deduction_retailer;
				}
				
				$ded_ret=$limit+$deduction_retailer;
				$remain_ret=$balance_retailer-$ded_ret;
				$ded_client=$limit+$deduction_client;
				$remain_client=$balance_client-$ded_client;
				$ded_admin=$limit+$deduction_admin;
				$remain_admin=$balance_admin-$ded_admin;
				$done_charges+=$deduction_retailer;
				////////////////////do with $limit
				$qry2="";			
				$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$limit', '$charges2', '$deduction_retailer', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
				$order_id=generate_mt_client_txn_child($qry2);
				if($order_id%1000==0)
				{
					//include_once('../functions/_zsms.php');
					//zsms("9896677625","Order No $order_id started on dated $datetime_datetime");
				}
				
				$qry3="";			
				$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$limit', '$deduction_admin', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
				$m_id=generate_mt_admin_txn($qry3);
				
				//update_mid_for_client
				$qry4="";
				$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
				mysql_query($qry4);
				
				//deduct_amount_for_retailer
				$qry5="";
				$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
				mysql_query($qry5);
				include_once('zf-WalletDistributed.php');
				update_user_balance($userid);
				
				//deduct_amount_for_client
				$qry6="";
				$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
				mysql_query($qry6);
				$tid=0;
				
				if($source==5)
				{
					//deduct_amount_for_admin
					$qry7="";
					$qry7="INSERT INTO $bankapi_parent_wallet.rt_ach_blyss(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
					mysql_query($qry7);
				}
				if($txn_status>0)
				{	
					include_once('zf-TxnSource3DmtApi.php');
/////LOKESH
					$resulted_data=fund_transfer2($m_id,$cno,$cname,$brid,$bacc,$bifsc,$method,$limit,$pan,$aadhar);
					$resulted_response=$resulted_data[6];
					$tid=$ASTransCode=$resulted_data[3];
					$ReferenceNumber=$resulted_data[4];
					$Status=$resulted_data[1];
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					if($resulted_data[1]=='SUCCESS')
						$txn_status=2;
					else if($resulted_data[1]=='FAILED')
						$txn_status=-4;
					
					//update tid for client_child
					mysql_query("update $bankapi_child_txn.txn_mt_child set tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';");
					
					//update response/tid for admin
					mysql_query("update $bankapi_parent_txn.txn_mt set response='$resulted_response', bank_ref_no='$ReferenceNumber', tid='$ASTransCode', response_message='$Status', mmt_status='$txn_status' where mmt_id='$m_id';");
					if($txn_status==2)
					{
						$result111= json_decode($resulted_response, true)[0];
						$BeneficiaryName111=$result111['BeneficiaryName'];
						$rname=$BeneficiaryName111;
						$query2="INSERT INTO bankatyf_common.eko_receiver_verified(bank, ifsc, receiver_acc_no, receiver_name, updated_on, source) VALUES ('$bbname','$bifsc','$bacc','$rname','$datetime','$source');";
						mysql_query($query2);
					}
				}
	$parents=show_my_parents($userid);
	$parent_01=$parents[0];
	$parent_02=$parents[1];
	$parent_03=$parents[2];
	$parent_04=$parents[3];
	$parent_05=$parents[4];
	$parent_06=$parents[5];
	$parent_07=$parents[6];
	$parent_08=$parents[7];
	$parent_09=$parents[8];
	$parent_10=$parents[9];
	$parent_11=$parents[10];
	$parent_12=$userid;
	
	$parent_01_rate=show_user_mt_rate_actual($parent_01, $source, $method, $limit);
	$parent_02_rate=show_user_mt_rate_actual($parent_02, $source, $method, $limit);
	$parent_03_rate=show_user_mt_rate_actual($parent_03, $source, $method, $limit);
	$parent_04_rate=show_user_mt_rate_actual($parent_04, $source, $method, $limit);
	$parent_05_rate=show_user_mt_rate_actual($parent_05, $source, $method, $limit);
	$parent_06_rate=show_user_mt_rate_actual($parent_06, $source, $method, $limit);
	$parent_07_rate=show_user_mt_rate_actual($parent_07, $source, $method, $limit);
	$parent_08_rate=show_user_mt_rate_actual($parent_08, $source, $method, $limit);
	$parent_09_rate=show_user_mt_rate_actual($parent_09, $source, $method, $limit);
	$parent_10_rate=show_user_mt_rate_actual($parent_10, $source, $method, $limit);
	$parent_11_rate=show_user_mt_rate_actual($parent_11, $source, $method, $limit);
	$parent_12_rate=show_user_mt_rate_actual($parent_12, $source, $method, $limit);
	
	$rcom=$deduction_retailer-$parent_12_rate;
	$rcom=number_format((float)$rcom, 2, '.', '');
				
				//level wise margin for client
				
				$qry11="insert into $bankapi_child_txn.txn_mt_child_margin value ('$order_id', '$txn_id', '$parent_01', '$parent_01_rate', '$parent_02', '$parent_02_rate', '$parent_03', '$parent_03_rate', '$parent_04', '$parent_04_rate', '$parent_05', '$parent_05_rate', '$parent_06', '$parent_06_rate', '$parent_07', '$parent_07_rate', '$parent_08', '$parent_08_rate', '$parent_09', '$parent_09_rate', '$parent_10', '$parent_10_rate', '$parent_11', '$parent_11_rate', '$parent_12', '$parent_12_rate', '$deduction_retailer')";
				mysql_query($qry11);
				
				//margin for admin
				
				$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$limit', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
				mysql_query($qry12);
				
				/***/
				$admin_rate=$deduction_admin;
				$client_rate=$deduction_client;
				$charged=$deduction_retailer;
				$lvl_1_id=$lvl_2_id=$lvl_3_id=$lvl_4_id=$lvl_5_id=$lvl_6_id=0;
				$lvl_7_id=$lvl_8_id=$lvl_9_id=$lvl_10_id=$lvl_11_id=$lvl_12_id=0;///
				$lvl_1_rate=$lvl_2_rate=$lvl_3_rate=$lvl_4_rate=$lvl_5_rate=$lvl_6_rate=0;
				$lvl_7_rate=$lvl_8_rate=$lvl_9_rate=$lvl_10_rate=$lvl_11_rate=$lvl_12_rate=0;
				$lvl_1_com=$lvl_2_com=$lvl_3_com=$lvl_4_com=$lvl_5_com=$lvl_6_com=0;
				$lvl_7_com=$lvl_8_com=$lvl_9_com=$lvl_10_com=$lvl_11_com=$lvl_12_com=0;///
				$lvl_1_tds=$lvl_2_tds=$lvl_3_tds=$lvl_4_tds=$lvl_5_tds=$lvl_6_tds=0;
				$lvl_7_tds=$lvl_8_tds=$lvl_9_tds=$lvl_10_tds=$lvl_11_tds=$lvl_12_tds=0;///
				$lvl_1_earn=$lvl_2_earn=$lvl_3_earn=$lvl_4_earn=$lvl_5_earn=$lvl_6_earn=0;
				$lvl_7_earn=$lvl_8_earn=$lvl_9_earn=$lvl_10_earn=$lvl_11_earn=$lvl_12_earn=0;///
				$retailer_gst=0;///
				$retailer_com=0;///
				$admin_fee=0;///
				$admin_gst=0;///
				$total_gst=0;	
				$gst_rate=0;//.20
				$earn_rate=1;//.80//.80*.95
				$tds_rate=0;//0//.80*.05

				
				$lvl_1_id=$parent_01;
				$lvl_2_id=$parent_02;
				$lvl_3_id=$parent_03;
				$lvl_4_id=$parent_04;
				$lvl_5_id=$parent_05;
				$lvl_6_id=$parent_06;
				$lvl_7_id=$parent_07;
				$lvl_8_id=$parent_08;
				$lvl_9_id=$parent_09;
				$lvl_10_id=$parent_10;
				$lvl_11_id=$parent_11;
				$lvl_12_id=$parent_12;
				$lvl_1_rate=$parent_01_rate;
				$lvl_2_rate=$parent_02_rate;
				$lvl_3_rate=$parent_03_rate;
				$lvl_4_rate=$parent_04_rate;
				$lvl_5_rate=$parent_05_rate;
				$lvl_6_rate=$parent_06_rate;
				$lvl_7_rate=$parent_07_rate;
				$lvl_8_rate=$parent_08_rate;
				$lvl_9_rate=$parent_09_rate;
				$lvl_10_rate=$parent_10_rate;
				$lvl_11_rate=$parent_11_rate;
				$lvl_12_rate=$parent_12_rate;
				/*
				if($lvl_2_rate>($limit*.01))
				$lvl_2_rate=$limit*.01;
				if($lvl_3_rate>($limit*.01))
				$lvl_3_rate=$limit*.01;
				if($lvl_4_rate>($limit*.01))
				$lvl_4_rate=$limit*.01;
				if($lvl_5_rate>($limit*.01))
				$lvl_5_rate=$limit*.01;
				if($lvl_6_rate>($limit*.01))
				$lvl_6_rate=$limit*.01;
				if($lvl_7_rate>($limit*.01))
				$lvl_7_rate=$limit*.01;
				if($lvl_8_rate>($limit*.01))
				$lvl_8_rate=$limit*.01;
				if($lvl_9_rate>($limit*.01))
				$lvl_9_rate=$limit*.01;
				if($lvl_10_rate>($limit*.01))
				$lvl_10_rate=$limit*.01;
				if($lvl_11_rate>($limit*.01))
				$lvl_11_rate=$limit*.01;
				if($lvl_12_rate>($limit*.01))
				$lvl_12_rate=$limit*.01;
				*/
				$lvl_12_com=$rcom;
				
				if($lvl_11_rate==0)
					$lvl_11_com=0;
				else if($lvl_11_rate!=0)
				$lvl_11_com=$lvl_12_rate-$lvl_11_rate;
			
				if($lvl_10_rate==0)
					$lvl_10_com=0;
				else if($lvl_10_rate!=0)
				{
					if($lvl_11_rate==0)
						$lvl_10_com=$lvl_12_rate-$lvl_10_rate;
					else
					$lvl_10_com=$lvl_11_rate-$lvl_10_rate;
				}
			
				if($lvl_9_rate==0)
					$lvl_9_com=0;
				else if($lvl_9_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0)
						$lvl_9_com=$lvl_12_rate-$lvl_9_rate;
					else if($lvl_10_rate==0)
						$lvl_9_com=$lvl_11_rate-$lvl_9_rate;
					else
					$lvl_9_com=$lvl_10_rate-$lvl_9_rate;
				}
			
				if($lvl_8_rate==0)
					$lvl_8_com=0;
				else if($lvl_8_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0)
						$lvl_8_com=$lvl_12_rate-$lvl_8_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0)
						$lvl_8_com=$lvl_11_rate-$lvl_8_rate;
					else if($lvl_9_rate==0)
						$lvl_8_com=$lvl_10_rate-$lvl_8_rate;
					else
						$lvl_8_com=$lvl_9_rate-$lvl_8_rate;
				}
			
				if($lvl_7_rate==0)
					$lvl_7_com=0;
				else if($lvl_7_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0)
						$lvl_7_com=$lvl_12_rate-$lvl_7_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0)
						$lvl_7_com=$lvl_11_rate-$lvl_7_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0)
						$lvl_7_com=$lvl_10_rate-$lvl_7_rate;
					else if($lvl_8_rate==0)
						$lvl_7_com=$lvl_9_rate-$lvl_7_rate;
					else
						$lvl_7_com=$lvl_8_rate-$lvl_7_rate;
				}
			
				if($lvl_6_rate==0)
					$lvl_6_com=0;
				else if($lvl_6_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_12_rate-$lvl_6_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_11_rate-$lvl_6_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_10_rate-$lvl_6_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_9_rate-$lvl_6_rate;
					else if($lvl_7_rate==0)
						$lvl_6_com=$lvl_8_rate-$lvl_6_rate;
					else
						$lvl_6_com=$lvl_7_rate-$lvl_6_rate;
				}
			
				if($lvl_5_rate==0)
					$lvl_5_com=0;
				else if($lvl_5_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_12_rate-$lvl_5_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_11_rate-$lvl_5_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_10_rate-$lvl_5_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_9_rate-$lvl_5_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_8_rate-$lvl_5_rate;
					else if($lvl_6_rate==0)
						$lvl_5_com=$lvl_7_rate-$lvl_5_rate;
					else
						$lvl_5_com=$lvl_6_rate-$lvl_5_rate;
				}
			
				if($lvl_4_rate==0)
					$lvl_4_com=0;
				else if($lvl_4_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_12_rate-$lvl_4_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_11_rate-$lvl_4_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_10_rate-$lvl_4_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_9_rate-$lvl_4_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_8_rate-$lvl_4_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_7_rate-$lvl_4_rate;
					else if($lvl_5_rate==0)
						$lvl_4_com=$lvl_6_rate-$lvl_4_rate;
					else
						$lvl_4_com=$lvl_5_rate-$lvl_4_rate;
				}
			
				if($lvl_3_rate==0)
					$lvl_3_com=0;
				else if($lvl_3_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_12_rate-$lvl_3_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_11_rate-$lvl_3_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_10_rate-$lvl_3_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_9_rate-$lvl_3_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_8_rate-$lvl_3_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_7_rate-$lvl_3_rate;
					else if($lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_6_rate-$lvl_3_rate;
					else if($lvl_4_rate==0)
						$lvl_3_com=$lvl_5_rate-$lvl_3_rate;
					else
						$lvl_3_com=$lvl_4_rate-$lvl_3_rate;
				}
			
				if($lvl_2_rate==0)
					$lvl_2_com=0;
				else if($lvl_2_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_12_rate-$lvl_2_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_11_rate-$lvl_2_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_10_rate-$lvl_2_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_9_rate-$lvl_2_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_8_rate-$lvl_2_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_7_rate-$lvl_2_rate;
					else if($lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_6_rate-$lvl_2_rate;
					else if($lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_5_rate-$lvl_2_rate;
					else if($lvl_3_rate==0)
						$lvl_2_com=$lvl_4_rate-$lvl_2_rate;
					else
						$lvl_2_com=$lvl_3_rate-$lvl_2_rate;
				}
			
				if($lvl_1_rate==0)
					$lvl_1_com=0;
				else if($lvl_1_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_12_rate-$lvl_1_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_11_rate-$lvl_1_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_10_rate-$lvl_1_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_9_rate-$lvl_1_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_8_rate-$lvl_1_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_7_rate-$lvl_1_rate;
					else if($lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_6_rate-$lvl_1_rate;
					else if($lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_5_rate-$lvl_1_rate;
					else if($lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_4_rate-$lvl_1_rate;
					else if($lvl_2_rate==0)
						$lvl_1_com=$lvl_3_rate-$lvl_1_rate;
					else
						$lvl_1_com=$lvl_2_rate-$lvl_1_rate;
				}
				/***/
				$lvl_1_tds=0;
				$lvl_1_earn=$lvl_1_com;

				$retailer_gst=($charged-$charges2)*$gst_rate;
				$retailer_gst=number_format((float)$retailer_gst, 5, '.', '');
				$retailer_com=$charged-$charges2-$retailer_gst;
				$retailer_com=number_format((float)$retailer_com, 5, '.', '');
				
				$admin_fee=($admin_rate*100)/118;
				$admin_fee=number_format((float)$admin_fee, 5, '.', '');
				$admin_gst=$admin_rate-$admin_fee;
				$admin_gst=number_format((float)$admin_gst, 5, '.', '');
				$total_gst+=number_format((float)($lvl_2_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_3_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_4_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_5_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_6_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_7_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_8_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_9_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_10_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_11_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_12_com*$gst_rate), 5, '.', '');
				
				$lvl_2_tds=number_format((float)($lvl_2_com*$tds_rate), 5, '.', '');
				$lvl_2_earn=number_format((float)($lvl_2_com-$lvl_2_tds), 5, '.', '');
				$lvl_3_tds=number_format((float)($lvl_3_com*$tds_rate), 5, '.', '');
				$lvl_3_earn=number_format((float)($lvl_3_com-$lvl_3_tds), 5, '.', '');
				$lvl_4_tds=number_format((float)($lvl_4_com*$tds_rate), 5, '.', '');
				$lvl_4_earn=number_format((float)($lvl_4_com-$lvl_4_tds), 5, '.', '');
				$lvl_5_tds=number_format((float)($lvl_5_com*$tds_rate), 5, '.', '');
				$lvl_5_earn=number_format((float)($lvl_5_com-$lvl_5_tds), 5, '.', '');
				$lvl_6_tds=number_format((float)($lvl_6_com*$tds_rate), 5, '.', '');
				$lvl_6_earn=number_format((float)($lvl_6_com-$lvl_6_tds), 5, '.', '');
				$lvl_7_tds=number_format((float)($lvl_7_com*$tds_rate), 5, '.', '');
				$lvl_7_earn=number_format((float)($lvl_7_com-$lvl_7_tds), 5, '.', '');
				$lvl_8_tds=number_format((float)($lvl_8_com*$tds_rate), 5, '.', '');
				$lvl_8_earn=number_format((float)($lvl_8_com-$lvl_8_tds), 5, '.', '');
				$lvl_9_tds=number_format((float)($lvl_9_com*$tds_rate), 5, '.', '');
				$lvl_9_earn=number_format((float)($lvl_9_com-$lvl_9_tds), 5, '.', '');
				$lvl_10_tds=number_format((float)($lvl_10_com*$tds_rate), 5, '.', '');
				$lvl_10_earn=number_format((float)($lvl_10_com-$lvl_10_tds), 5, '.', '');
				$lvl_11_tds=number_format((float)($lvl_11_com*$tds_rate), 5, '.', '');
				$lvl_11_earn=number_format((float)($lvl_11_com-$lvl_11_tds), 5, '.', '');
				$lvl_12_tds=number_format((float)($lvl_12_com*$tds_rate), 5, '.', '');
				$lvl_12_earn=number_format((float)($lvl_12_com-$lvl_12_tds), 5, '.', '');
				
				//$clientdb="$bankapi_child".$clienttype."_".$clientid;
				$client_com_gen_qry="INSERT INTO $bankapi_child_txn.com_generated(order_id, tid, source, type, method, date_time, user_id, amount, charged, retailer_gst, retailer_com, admin_gst, admin_fee, lvl_1_id, lvl_1_com, lvl_1_tds, lvl_1_earn, lvl_2_id, lvl_2_com, lvl_2_tds, lvl_2_earn, lvl_3_id, lvl_3_com, lvl_3_tds, lvl_3_earn, lvl_4_id, lvl_4_com, lvl_4_tds, lvl_4_earn, lvl_5_id, lvl_5_com, lvl_5_tds, lvl_5_earn, lvl_6_id, lvl_6_com, lvl_6_tds, lvl_6_earn, lvl_7_id, lvl_7_com, lvl_7_tds, lvl_7_earn, lvl_8_id, lvl_8_com, lvl_8_tds, lvl_8_earn, lvl_9_id, lvl_9_com, lvl_9_tds, lvl_9_earn, lvl_10_id, lvl_10_com, lvl_10_tds, lvl_10_earn, lvl_11_id, lvl_11_com, lvl_11_tds, lvl_11_earn, lvl_12_id, lvl_12_com, lvl_12_tds, lvl_12_earn) value ('$order_id', '$tid', '$source', '$type', '$method', '$datetime', '$userid', '$limit', '$charged', '$retailer_gst', '$retailer_com', '$admin_gst', '$admin_fee', '$lvl_1_id', '$lvl_1_com', '$lvl_1_tds', '$lvl_1_earn', '$lvl_2_id', '$lvl_2_com', '$lvl_2_tds', '$lvl_2_earn', '$lvl_3_id', '$lvl_3_com', '$lvl_3_tds', '$lvl_3_earn', '$lvl_4_id', '$lvl_4_com', '$lvl_4_tds', '$lvl_4_earn', '$lvl_5_id', '$lvl_5_com', '$lvl_5_tds', '$lvl_5_earn', '$lvl_6_id', '$lvl_6_com', '$lvl_6_tds', '$lvl_6_earn', '$lvl_7_id', '$lvl_7_com', '$lvl_7_tds', '$lvl_7_earn', '$lvl_8_id', '$lvl_8_com', '$lvl_8_tds', '$lvl_8_earn', '$lvl_9_id', '$lvl_9_com', '$lvl_9_tds', '$lvl_9_earn', '$lvl_10_id', '$lvl_10_com', '$lvl_10_tds', '$lvl_10_earn', '$lvl_11_id', '$lvl_11_com', '$lvl_11_tds', '$lvl_11_earn', '$lvl_12_id', '$lvl_12_com', '$lvl_12_tds', '$lvl_12_earn')";
				mysql_query($client_com_gen_qry);
				$admin_earn=$lvl_1_earn;
				$team_earn=$lvl_2_earn+$lvl_3_earn+$lvl_4_earn+$lvl_5_earn+$lvl_6_earn+$lvl_7_earn+$lvl_8_earn+$lvl_9_earn+$lvl_10_earn+$lvl_11_earn+$lvl_12_earn;
				$total_tds=$lvl_2_tds+$lvl_3_tds+$lvl_4_tds+$lvl_5_tds+$lvl_6_tds+$lvl_7_tds+$lvl_8_tds+$lvl_9_tds+$lvl_10_tds+$lvl_11_tds+$lvl_12_tds;
				$total_amt=$admin_earn+$team_earn+$total_gst+$total_tds;
				
				$lvl_1_earn=$admin_earn+$total_gst+$total_tds;
				$lvl1ern=$lvl_1_earn+$client_rate;
				
				if($lvl_1_id!=0 && $lvl1ern!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_1_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl1ern', '$client_rate');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_2_id!=0 && $lvl_2_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_2_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_2_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_3_id!=0 && $lvl_3_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_3_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_3_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_4_id!=0 && $lvl_4_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_4_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_4_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_5_id!=0 && $lvl_5_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_5_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_5_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_6_id!=0 && $lvl_6_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_6_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_6_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_7_id!=0 && $lvl_7_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_7_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_7_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_8_id!=0 && $lvl_8_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_8_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_8_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_9_id!=0 && $lvl_9_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_9_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_9_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_10_id!=0 && $lvl_10_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_10_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_10_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_11_id!=0 && $lvl_11_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_11_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_11_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_12_id!=0 && $lvl_12_earn!=0)
				{
					$details="My Earnings from order no: $order_id at $datetime ($userid : $lvl_12_id) ($rcom : $lvl_12_earn)";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_12_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_12_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
			}
			if($amt<$limit && $amt>0)
			{
				sleep(1);
				$balance_retailer=show_txn_user_balance($userid);
				$balance_client=show_txn_client_balance();
				$balance_admin=show_txn_admin_balance($source);
				
				$deduction_retailer=show_user_mt_rate($userid, $source, $method, $amt);
				$deduction_client=show_client_mt_rate($source, $amt);
				$deduction_admin=show_admin_mt_rate($source, $method, $amt);
				
				$charges2=0;
				if($charges2<$deduction_retailer)
					$charges2=$deduction_retailer;
				$deduction_retailer=$amt*$charged123/$amount;
				$deduction_retailer=$charged123-$done_charges;
				if($charges2>$deduction_retailer)
					$deduction_retailer=$charges2;
				
				$ded_ret=$amt+$deduction_retailer;
				$remain_ret=$balance_retailer-$ded_ret;
				$ded_client=$amt+$deduction_client;
				$remain_client=$balance_client-$ded_client;
				$ded_admin=$amt+$deduction_admin;
				$remain_admin=$balance_admin-$ded_admin;
				////////////////////do with $amt
				$qry2="";			
				$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$amt', '$charges2', '$deduction_retailer', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
				$order_id=generate_mt_client_txn_child($qry2);
				if($order_id%1000==0)
				{
					//include_once('../functions/_zsms.php');
					//zsms("9896677625","Order No $order_id started on dated $datetime_datetime");
				}
				
				$qry3="";			
				$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$amt', '$deduction_admin', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
				$m_id=generate_mt_admin_txn($qry3);
				
				//update_mid_for_client
				$qry4="";
				$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
				mysql_query($qry4);
				
				//deduct_amount_for_retailer
				$qry5="";
				$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
				mysql_query($qry5);
				include_once('zf-WalletDistributed.php');
				update_user_balance($userid);
				
				//deduct_amount_for_client
				$qry6="";
				$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
				mysql_query($qry6);
				$tid=0;
				
				if($source==5)
				{
					//deduct_amount_for_admin
					$qry7="";
					$qry7="INSERT INTO $bankapi_parent_wallet.rt_ach_blyss(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
					mysql_query($qry7);
				}
				if($txn_status>0)
				{	
					include_once('zf-TxnSource3DmtApi.php');
/////LOKESH
					$resulted_data=fund_transfer2($m_id,$cno,$cname,$brid,$bacc,$bifsc,$method,$amt,$pan,$aadhar);
					$resulted_response=$resulted_data[6];
					$tid=$ASTransCode=$resulted_data[3];
					$ReferenceNumber=$resulted_data[4];
					$Status=$resulted_data[1];
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					if($resulted_data[1]=='SUCCESS')
						$txn_status=2;
					else if($resulted_data[1]=='FAILED')
						$txn_status=-4;
					
					//update tid for client_child
					mysql_query("update $bankapi_child_txn.txn_mt_child set tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';");
					
					//update response/tid for admin
					mysql_query("update $bankapi_parent_txn.txn_mt set response='$resulted_response', bank_ref_no='$ReferenceNumber', tid='$ASTransCode', response_message='$Status', mmt_status='$txn_status' where mmt_id='$m_id';");
					if($txn_status==2)
					{
						$result111= json_decode($resulted_response, true)[0];
						$BeneficiaryName111=$result111['BeneficiaryName'];
						$rname=$BeneficiaryName111;
						$query2="INSERT INTO bankatyf_common.eko_receiver_verified(bank, ifsc, receiver_acc_no, receiver_name, updated_on, source) VALUES ('$bbname','$bifsc','$bacc','$rname','$datetime','$source');";
						mysql_query($query2);
					}
				}
			
	$parents=show_my_parents($userid);
	$parent_01=$parents[0];
	$parent_02=$parents[1];
	$parent_03=$parents[2];
	$parent_04=$parents[3];
	$parent_05=$parents[4];
	$parent_06=$parents[5];
	$parent_07=$parents[6];
	$parent_08=$parents[7];
	$parent_09=$parents[8];
	$parent_10=$parents[9];
	$parent_11=$parents[10];
	$parent_12=$userid;
	
	$parent_01_rate=show_user_mt_rate_actual($parent_01, $source, $method, $amt);
	$parent_02_rate=show_user_mt_rate_actual($parent_02, $source, $method, $amt);
	$parent_03_rate=show_user_mt_rate_actual($parent_03, $source, $method, $amt);
	$parent_04_rate=show_user_mt_rate_actual($parent_04, $source, $method, $amt);
	$parent_05_rate=show_user_mt_rate_actual($parent_05, $source, $method, $amt);
	$parent_06_rate=show_user_mt_rate_actual($parent_06, $source, $method, $amt);
	$parent_07_rate=show_user_mt_rate_actual($parent_07, $source, $method, $amt);
	$parent_08_rate=show_user_mt_rate_actual($parent_08, $source, $method, $amt);
	$parent_09_rate=show_user_mt_rate_actual($parent_09, $source, $method, $amt);
	$parent_10_rate=show_user_mt_rate_actual($parent_10, $source, $method, $amt);
	$parent_11_rate=show_user_mt_rate_actual($parent_11, $source, $method, $amt);
	$parent_12_rate=show_user_mt_rate_actual($parent_12, $source, $method, $amt);
	
	$rcom=$deduction_retailer-$parent_12_rate;
	$rcom=number_format((float)$rcom, 2, '.', '');
				
				//level wise margin for client
				
				$qry11="insert into $bankapi_child_txn.txn_mt_child_margin value ('$order_id', '$txn_id', '$parent_01', '$parent_01_rate', '$parent_02', '$parent_02_rate', '$parent_03', '$parent_03_rate', '$parent_04', '$parent_04_rate', '$parent_05', '$parent_05_rate', '$parent_06', '$parent_06_rate', '$parent_07', '$parent_07_rate', '$parent_08', '$parent_08_rate', '$parent_09', '$parent_09_rate', '$parent_10', '$parent_10_rate', '$parent_11', '$parent_11_rate', '$parent_12', '$parent_12_rate', '$deduction_retailer')";
				mysql_query($qry11);
				
				//margin for admin
				
				$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$amt', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
				mysql_query($qry12);
				
				/***/
				$admin_rate=$deduction_admin;
				$client_rate=$deduction_client;
				$charged=$deduction_retailer;
				$lvl_1_id=$lvl_2_id=$lvl_3_id=$lvl_4_id=$lvl_5_id=$lvl_6_id=0;
				$lvl_7_id=$lvl_8_id=$lvl_9_id=$lvl_10_id=$lvl_11_id=$lvl_12_id=0;///
				$lvl_1_rate=$lvl_2_rate=$lvl_3_rate=$lvl_4_rate=$lvl_5_rate=$lvl_6_rate=0;
				$lvl_7_rate=$lvl_8_rate=$lvl_9_rate=$lvl_10_rate=$lvl_11_rate=$lvl_12_rate=0;
				$lvl_1_com=$lvl_2_com=$lvl_3_com=$lvl_4_com=$lvl_5_com=$lvl_6_com=0;
				$lvl_7_com=$lvl_8_com=$lvl_9_com=$lvl_10_com=$lvl_11_com=$lvl_12_com=0;///
				$lvl_1_tds=$lvl_2_tds=$lvl_3_tds=$lvl_4_tds=$lvl_5_tds=$lvl_6_tds=0;
				$lvl_7_tds=$lvl_8_tds=$lvl_9_tds=$lvl_10_tds=$lvl_11_tds=$lvl_12_tds=0;///
				$lvl_1_earn=$lvl_2_earn=$lvl_3_earn=$lvl_4_earn=$lvl_5_earn=$lvl_6_earn=0;
				$lvl_7_earn=$lvl_8_earn=$lvl_9_earn=$lvl_10_earn=$lvl_11_earn=$lvl_12_earn=0;///
				$retailer_gst=0;///
				$retailer_com=0;///
				$admin_fee=0;///
				$admin_gst=0;///
				$total_gst=0;	
				$gst_rate=0;//.20
				$earn_rate=1;//.80//.80*.95
				$tds_rate=0;//0//.80*.05

				
				$lvl_1_id=$parent_01;
				$lvl_2_id=$parent_02;
				$lvl_3_id=$parent_03;
				$lvl_4_id=$parent_04;
				$lvl_5_id=$parent_05;
				$lvl_6_id=$parent_06;
				$lvl_7_id=$parent_07;
				$lvl_8_id=$parent_08;
				$lvl_9_id=$parent_09;
				$lvl_10_id=$parent_10;
				$lvl_11_id=$parent_11;
				$lvl_12_id=$parent_12;
				$lvl_1_rate=$parent_01_rate;
				$lvl_2_rate=$parent_02_rate;
				$lvl_3_rate=$parent_03_rate;
				$lvl_4_rate=$parent_04_rate;
				$lvl_5_rate=$parent_05_rate;
				$lvl_6_rate=$parent_06_rate;
				$lvl_7_rate=$parent_07_rate;
				$lvl_8_rate=$parent_08_rate;
				$lvl_9_rate=$parent_09_rate;
				$lvl_10_rate=$parent_10_rate;
				$lvl_11_rate=$parent_11_rate;
				$lvl_12_rate=$parent_12_rate;
				/*
				if($lvl_2_rate>($limit*.01))
				$lvl_2_rate=$limit*.01;
				if($lvl_3_rate>($limit*.01))
				$lvl_3_rate=$limit*.01;
				if($lvl_4_rate>($limit*.01))
				$lvl_4_rate=$limit*.01;
				if($lvl_5_rate>($limit*.01))
				$lvl_5_rate=$limit*.01;
				if($lvl_6_rate>($limit*.01))
				$lvl_6_rate=$limit*.01;
				if($lvl_7_rate>($limit*.01))
				$lvl_7_rate=$limit*.01;
				if($lvl_8_rate>($limit*.01))
				$lvl_8_rate=$limit*.01;
				if($lvl_9_rate>($limit*.01))
				$lvl_9_rate=$limit*.01;
				if($lvl_10_rate>($limit*.01))
				$lvl_10_rate=$limit*.01;
				if($lvl_11_rate>($limit*.01))
				$lvl_11_rate=$limit*.01;
				if($lvl_12_rate>($limit*.01))
				$lvl_12_rate=$limit*.01;
				*/
				$lvl_12_com=$rcom;
				
				if($lvl_11_rate==0)
					$lvl_11_com=0;
				else if($lvl_11_rate!=0)
				$lvl_11_com=$lvl_12_rate-$lvl_11_rate;
			
				if($lvl_10_rate==0)
					$lvl_10_com=0;
				else if($lvl_10_rate!=0)
				{
					if($lvl_11_rate==0)
						$lvl_10_com=$lvl_12_rate-$lvl_10_rate;
					else
					$lvl_10_com=$lvl_11_rate-$lvl_10_rate;
				}
			
				if($lvl_9_rate==0)
					$lvl_9_com=0;
				else if($lvl_9_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0)
						$lvl_9_com=$lvl_12_rate-$lvl_9_rate;
					else if($lvl_10_rate==0)
						$lvl_9_com=$lvl_11_rate-$lvl_9_rate;
					else
					$lvl_9_com=$lvl_10_rate-$lvl_9_rate;
				}
			
				if($lvl_8_rate==0)
					$lvl_8_com=0;
				else if($lvl_8_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0)
						$lvl_8_com=$lvl_12_rate-$lvl_8_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0)
						$lvl_8_com=$lvl_11_rate-$lvl_8_rate;
					else if($lvl_9_rate==0)
						$lvl_8_com=$lvl_10_rate-$lvl_8_rate;
					else
						$lvl_8_com=$lvl_9_rate-$lvl_8_rate;
				}
			
				if($lvl_7_rate==0)
					$lvl_7_com=0;
				else if($lvl_7_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0)
						$lvl_7_com=$lvl_12_rate-$lvl_7_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0)
						$lvl_7_com=$lvl_11_rate-$lvl_7_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0)
						$lvl_7_com=$lvl_10_rate-$lvl_7_rate;
					else if($lvl_8_rate==0)
						$lvl_7_com=$lvl_9_rate-$lvl_7_rate;
					else
						$lvl_7_com=$lvl_8_rate-$lvl_7_rate;
				}
			
				if($lvl_6_rate==0)
					$lvl_6_com=0;
				else if($lvl_6_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_12_rate-$lvl_6_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_11_rate-$lvl_6_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_10_rate-$lvl_6_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0)
						$lvl_6_com=$lvl_9_rate-$lvl_6_rate;
					else if($lvl_7_rate==0)
						$lvl_6_com=$lvl_8_rate-$lvl_6_rate;
					else
						$lvl_6_com=$lvl_7_rate-$lvl_6_rate;
				}
			
				if($lvl_5_rate==0)
					$lvl_5_com=0;
				else if($lvl_5_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_12_rate-$lvl_5_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_11_rate-$lvl_5_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_10_rate-$lvl_5_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_9_rate-$lvl_5_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0)
						$lvl_5_com=$lvl_8_rate-$lvl_5_rate;
					else if($lvl_6_rate==0)
						$lvl_5_com=$lvl_7_rate-$lvl_5_rate;
					else
						$lvl_5_com=$lvl_6_rate-$lvl_5_rate;
				}
			
				if($lvl_4_rate==0)
					$lvl_4_com=0;
				else if($lvl_4_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_12_rate-$lvl_4_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_11_rate-$lvl_4_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_10_rate-$lvl_4_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_9_rate-$lvl_4_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_8_rate-$lvl_4_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0)
						$lvl_4_com=$lvl_7_rate-$lvl_4_rate;
					else if($lvl_5_rate==0)
						$lvl_4_com=$lvl_6_rate-$lvl_4_rate;
					else
						$lvl_4_com=$lvl_5_rate-$lvl_4_rate;
				}
			
				if($lvl_3_rate==0)
					$lvl_3_com=0;
				else if($lvl_3_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_12_rate-$lvl_3_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_11_rate-$lvl_3_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_10_rate-$lvl_3_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_9_rate-$lvl_3_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_8_rate-$lvl_3_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_7_rate-$lvl_3_rate;
					else if($lvl_5_rate==0 && $lvl_4_rate==0)
						$lvl_3_com=$lvl_6_rate-$lvl_3_rate;
					else if($lvl_4_rate==0)
						$lvl_3_com=$lvl_5_rate-$lvl_3_rate;
					else
						$lvl_3_com=$lvl_4_rate-$lvl_3_rate;
				}
			
				if($lvl_2_rate==0)
					$lvl_2_com=0;
				else if($lvl_2_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_12_rate-$lvl_2_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_11_rate-$lvl_2_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_10_rate-$lvl_2_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_9_rate-$lvl_2_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_8_rate-$lvl_2_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_7_rate-$lvl_2_rate;
					else if($lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_6_rate-$lvl_2_rate;
					else if($lvl_4_rate==0 && $lvl_3_rate==0)
						$lvl_2_com=$lvl_5_rate-$lvl_2_rate;
					else if($lvl_3_rate==0)
						$lvl_2_com=$lvl_4_rate-$lvl_2_rate;
					else
						$lvl_2_com=$lvl_3_rate-$lvl_2_rate;
				}
			
				if($lvl_1_rate==0)
					$lvl_1_com=0;
				else if($lvl_1_rate!=0)
				{
					if($lvl_11_rate==0 && $lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_12_rate-$lvl_1_rate;
					else if($lvl_10_rate==0 && $lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_11_rate-$lvl_1_rate;
					else if($lvl_9_rate==0 && $lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_10_rate-$lvl_1_rate;
					else if($lvl_8_rate==0 && $lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_9_rate-$lvl_1_rate;
					else if($lvl_7_rate==0 && $lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_8_rate-$lvl_1_rate;
					else if($lvl_6_rate==0 && $lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_7_rate-$lvl_1_rate;
					else if($lvl_5_rate==0 && $lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_6_rate-$lvl_1_rate;
					else if($lvl_4_rate==0 && $lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_5_rate-$lvl_1_rate;
					else if($lvl_3_rate==0 && $lvl_2_rate==0)
						$lvl_1_com=$lvl_4_rate-$lvl_1_rate;
					else if($lvl_2_rate==0)
						$lvl_1_com=$lvl_3_rate-$lvl_1_rate;
					else
						$lvl_1_com=$lvl_2_rate-$lvl_1_rate;
				}
				/***/
				$lvl_1_tds=0;
				$lvl_1_earn=$lvl_1_com;

				$retailer_gst=($charged-$charges2)*$gst_rate;
				$retailer_gst=number_format((float)$retailer_gst, 5, '.', '');
				$retailer_com=$charged-$charges2-$retailer_gst;
				$retailer_com=number_format((float)$retailer_com, 5, '.', '');
				
				$admin_fee=($admin_rate*100)/118;
				$admin_fee=number_format((float)$admin_fee, 5, '.', '');
				$admin_gst=$admin_rate-$admin_fee;
				$admin_gst=number_format((float)$admin_gst, 5, '.', '');
				$total_gst+=number_format((float)($lvl_2_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_3_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_4_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_5_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_6_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_7_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_8_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_9_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_10_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_11_com*$gst_rate), 5, '.', '');
				$total_gst+=number_format((float)($lvl_12_com*$gst_rate), 5, '.', '');
				
				$lvl_2_tds=number_format((float)($lvl_2_com*$tds_rate), 5, '.', '');
				$lvl_2_earn=number_format((float)($lvl_2_com-$lvl_2_tds), 5, '.', '');
				$lvl_3_tds=number_format((float)($lvl_3_com*$tds_rate), 5, '.', '');
				$lvl_3_earn=number_format((float)($lvl_3_com-$lvl_3_tds), 5, '.', '');
				$lvl_4_tds=number_format((float)($lvl_4_com*$tds_rate), 5, '.', '');
				$lvl_4_earn=number_format((float)($lvl_4_com-$lvl_4_tds), 5, '.', '');
				$lvl_5_tds=number_format((float)($lvl_5_com*$tds_rate), 5, '.', '');
				$lvl_5_earn=number_format((float)($lvl_5_com-$lvl_5_tds), 5, '.', '');
				$lvl_6_tds=number_format((float)($lvl_6_com*$tds_rate), 5, '.', '');
				$lvl_6_earn=number_format((float)($lvl_6_com-$lvl_6_tds), 5, '.', '');
				$lvl_7_tds=number_format((float)($lvl_7_com*$tds_rate), 5, '.', '');
				$lvl_7_earn=number_format((float)($lvl_7_com-$lvl_7_tds), 5, '.', '');
				$lvl_8_tds=number_format((float)($lvl_8_com*$tds_rate), 5, '.', '');
				$lvl_8_earn=number_format((float)($lvl_8_com-$lvl_8_tds), 5, '.', '');
				$lvl_9_tds=number_format((float)($lvl_9_com*$tds_rate), 5, '.', '');
				$lvl_9_earn=number_format((float)($lvl_9_com-$lvl_9_tds), 5, '.', '');
				$lvl_10_tds=number_format((float)($lvl_10_com*$tds_rate), 5, '.', '');
				$lvl_10_earn=number_format((float)($lvl_10_com-$lvl_10_tds), 5, '.', '');
				$lvl_11_tds=number_format((float)($lvl_11_com*$tds_rate), 5, '.', '');
				$lvl_11_earn=number_format((float)($lvl_11_com-$lvl_11_tds), 5, '.', '');
				$lvl_12_tds=number_format((float)($lvl_12_com*$tds_rate), 5, '.', '');
				$lvl_12_earn=number_format((float)($lvl_12_com-$lvl_12_tds), 5, '.', '');
				
				//$clientdb="$bankapi_child".$clienttype."_".$clientid;
				$client_com_gen_qry="INSERT INTO $bankapi_child_txn.com_generated(order_id, tid, source, type, method, date_time, user_id, amount, charged, retailer_gst, retailer_com, admin_gst, admin_fee, lvl_1_id, lvl_1_com, lvl_1_tds, lvl_1_earn, lvl_2_id, lvl_2_com, lvl_2_tds, lvl_2_earn, lvl_3_id, lvl_3_com, lvl_3_tds, lvl_3_earn, lvl_4_id, lvl_4_com, lvl_4_tds, lvl_4_earn, lvl_5_id, lvl_5_com, lvl_5_tds, lvl_5_earn, lvl_6_id, lvl_6_com, lvl_6_tds, lvl_6_earn, lvl_7_id, lvl_7_com, lvl_7_tds, lvl_7_earn, lvl_8_id, lvl_8_com, lvl_8_tds, lvl_8_earn, lvl_9_id, lvl_9_com, lvl_9_tds, lvl_9_earn, lvl_10_id, lvl_10_com, lvl_10_tds, lvl_10_earn, lvl_11_id, lvl_11_com, lvl_11_tds, lvl_11_earn, lvl_12_id, lvl_12_com, lvl_12_tds, lvl_12_earn) value ('$order_id', '$tid', '$source', '$type', '$method', '$datetime', '$userid', '$amt', '$charged', '$retailer_gst', '$retailer_com', '$admin_gst', '$admin_fee', '$lvl_1_id', '$lvl_1_com', '$lvl_1_tds', '$lvl_1_earn', '$lvl_2_id', '$lvl_2_com', '$lvl_2_tds', '$lvl_2_earn', '$lvl_3_id', '$lvl_3_com', '$lvl_3_tds', '$lvl_3_earn', '$lvl_4_id', '$lvl_4_com', '$lvl_4_tds', '$lvl_4_earn', '$lvl_5_id', '$lvl_5_com', '$lvl_5_tds', '$lvl_5_earn', '$lvl_6_id', '$lvl_6_com', '$lvl_6_tds', '$lvl_6_earn', '$lvl_7_id', '$lvl_7_com', '$lvl_7_tds', '$lvl_7_earn', '$lvl_8_id', '$lvl_8_com', '$lvl_8_tds', '$lvl_8_earn', '$lvl_9_id', '$lvl_9_com', '$lvl_9_tds', '$lvl_9_earn', '$lvl_10_id', '$lvl_10_com', '$lvl_10_tds', '$lvl_10_earn', '$lvl_11_id', '$lvl_11_com', '$lvl_11_tds', '$lvl_11_earn', '$lvl_12_id', '$lvl_12_com', '$lvl_12_tds', '$lvl_12_earn')";
				mysql_query($client_com_gen_qry);
				$admin_earn=$lvl_1_earn;
				$team_earn=$lvl_2_earn+$lvl_3_earn+$lvl_4_earn+$lvl_5_earn+$lvl_6_earn+$lvl_7_earn+$lvl_8_earn+$lvl_9_earn+$lvl_10_earn+$lvl_11_earn+$lvl_12_earn;
				$total_tds=$lvl_2_tds+$lvl_3_tds+$lvl_4_tds+$lvl_5_tds+$lvl_6_tds+$lvl_7_tds+$lvl_8_tds+$lvl_9_tds+$lvl_10_tds+$lvl_11_tds+$lvl_12_tds;
				$total_amt=$admin_earn+$team_earn+$total_gst+$total_tds;
				
				$lvl_1_earn=$admin_earn+$total_gst+$total_tds;
				$lvl1ern=$lvl_1_earn+$client_rate;
				
				if($lvl_1_id!=0 && $lvl1ern!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_1_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl1ern', '$client_rate');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_2_id!=0 && $lvl_2_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_2_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_2_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_3_id!=0 && $lvl_3_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_3_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_3_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_4_id!=0 && $lvl_4_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_4_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_4_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_5_id!=0 && $lvl_5_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_5_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_5_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_6_id!=0 && $lvl_6_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_6_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_6_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_7_id!=0 && $lvl_7_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_7_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_7_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_8_id!=0 && $lvl_8_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_8_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_8_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_9_id!=0 && $lvl_9_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_9_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_9_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_10_id!=0 && $lvl_10_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_10_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_10_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_11_id!=0 && $lvl_11_earn!=0)
				{
					$details="Earnings from order no: $order_id of user id: $userid at $datetime";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_11_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_11_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
				if($lvl_12_id!=0 && $lvl_12_earn!=0)
				{
					$details="My Earnings from order no: $order_id at $datetime ($userid : $lvl_12_id) ($rcom : $lvl_12_earn)";
					$client_com_paid_qry="INSERT INTO $bankapi_child_txn.com_paid_child(order_id, user_id, source, type, method, date_time, details, cr, dr) value ('$order_id', '$lvl_12_id', '$source', '$type', '$method', '$datetime', '$details', '$lvl_12_earn', '0');";
					mysql_query($client_com_paid_qry);
				}
			}
		}
	}
	return $err;
}

function mid_by_order($order)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	
	$mid=0;
	$query="SELECT * FROM $bankapi_child_txn.txn_mt_child where order_id='$order';";
	$result=mysql_query($query);
	while($r = mysql_fetch_array($result)) 
	{
		$mid=$r['mid'];
	}
	return $mid;
}

function type_by_mid($order)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	
	$mid=0;
	$query="SELECT * FROM $bankapi_parent_txn.txn_mt where mmt_id='$order';";
	$result=mysql_query($query);
	while($r = mysql_fetch_array($result)) 
	{
		$mid=$r['type'];
	}
	return $mid;
}

function amt_by_mid($order)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	
	$mid=0;
	$query="SELECT * FROM $bankapi_parent_txn.txn_mt where mmt_id='$order';";
	$result=mysql_query($query);
	while($r = mysql_fetch_array($result)) 
	{
		$mid=$r['amount'];
	}
	return $mid;
}

function show_ip()
{
	$ipaddress1 = "";
	if (isset($_SERVER['HTTP_CLIENT_IP']))//check ip from share internet
		$ipaddress1 = $_SERVER['HTTP_CLIENT_IP'];
	else if(isset($_SERVER['HTTP_X_FORWARDED_FOR']))//to check ip is pass from proxy
		$ipaddress1 = $_SERVER['HTTP_X_FORWARDED_FOR'];
	else if(isset($_SERVER['HTTP_X_FORWARDED']))
		$ipaddress1 = $_SERVER['HTTP_X_FORWARDED'];
	else if(isset($_SERVER['HTTP_FORWARDED_FOR']))
		$ipaddress1 = $_SERVER['HTTP_FORWARDED_FOR'];
	else if(isset($_SERVER['HTTP_FORWARDED']))
		$ipaddress1 = $_SERVER['HTTP_FORWARDED'];
	else if(isset($_SERVER['REMOTE_ADDR']))
		$ipaddress1 = $_SERVER['REMOTE_ADDR'];
	else
		$ipaddress1 = 'UNKNOWN';
		
		
	$ipaddress2 = "";
	if (getenv('HTTP_CLIENT_IP'))//check ip from share internet
		$ipaddress2 = getenv('HTTP_CLIENT_IP');
	else if(getenv('HTTP_X_FORWARDED_FOR'))//to check ip is pass from proxy
		$ipaddress2 = getenv('HTTP_X_FORWARDED_FOR');
	else if(getenv('HTTP_X_FORWARDED'))
		$ipaddress2 = getenv('HTTP_X_FORWARDED');
	else if(getenv('HTTP_FORWARDED_FOR'))
		$ipaddress2 = getenv('HTTP_FORWARDED_FOR');
	else if(getenv('HTTP_FORWARDED'))
		$ipaddress2 = getenv('HTTP_FORWARDED');
	else if(getenv('REMOTE_ADDR'))
		$ipaddress2 = getenv('REMOTE_ADDR');
	else
		$ipaddress2 = 'UNKNOWN';
		
	$final_ip=$ipaddress1."<br>".$ipaddress2;
	$browser=$_SERVER['HTTP_USER_AGENT'];
	
	$main_ip="$final_ip <br><br> $browser";
	return $main_ip;
}

function generate_mt_client_txn_parent($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_mt_client_txn_child($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_mt_admin_txn($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_rc_client_txn($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_rc_admin_txn($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function refund_amount($oid,$mid,$tid,$refund_source_tid,$source)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	include_once('zf-WalletDistributed.php');
	// start refund to refund_source_tid//refund_admin_tid//refund_client_tid//refund_retailer_tid
	$refund_admin_tid=$refund_client_tid=$refund_retailer_tid=0;
	// get user id of order id
	$uid=0;
	$admin_charges=0;
	$client_charges=0;
	$retailer_charges=0;
	$qry3="select * from $bankapi_parent_txn.txn_mt where mmt_id='$mid'";
	$res3=mysql_query($qry3);
	while($rs3=mysql_fetch_array($res3))
	{
		$uid=$rs3['user_id'];
	}
	
	// get order deducted amount of admin wallet with wallet id
	if($source==5)
	{
		$query_ref="select * from $bankapi_parent_wallet.rt_ach_blyss where user_id='$uid' and client_id='$clientdbid' and client_order_id='$oid' and transaction_type='2' order by wallet_id desc limit 0,1";
		$result_ref=mysql_query($query_ref);
		while($rs_ref = mysql_fetch_array($result_ref))
		{
			$admin_charges=$rs_ref['amount_dr'];
		}
	}
	
	// get order deducted amount of client wallet with wallet id
	$query_ref="select * from $bankapi_child_wallet.realtime where user_id='$uid' and client_order_id='$oid' and transaction_type='2' order by wallet_id desc limit 0,1";
	$result_ref=mysql_query($query_ref);
	while($rs_ref = mysql_fetch_array($result_ref))
	{
		$client_charges=$rs_ref['amount_dr'];
	}
	
	
	$query_ref="select * from $bankapi_child_wallet.distribution where user_id='$uid' and user_id2='0' and order_id='$oid' and transaction_type='6'";
	$result_ref=mysql_query($query_ref);
	while($rs_ref = mysql_fetch_array($result_ref))
	{
		$retailer_charges=$rs_ref['amount_dr'];
	}
	
	$filled_remarks="Money Transfer order $oid refunded";
	//get last balance of admin
	$balance_admin=show_txn_admin_balance($source);
	$balance_admin_new=$balance_admin+$admin_charges;
	
	$src_ref=0;
	$src_q="select * from $bankapi_parent_wallet.rt_ach_blyss where transaction_type='3' and client_id='$clientdbid' and user_id='$uid' and client_order_id='$oid';";
	$src_res=mysql_query($src_q);
	while($src_rs = mysql_fetch_assoc($src_res))
	{
		$src_ref++;
	}
	
	if($source==5 && $src_ref==0)
	{
		//refund order to admin
		$query4b="INSERT INTO $bankapi_parent_wallet.rt_ach_blyss (wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) VALUES ('$datetime_date', '$datetime_time', '$clientdbid', '$uid', '$oid', '0', '3', '$filled_remarks', '$balance_admin', '$admin_charges', '0.00', '$balance_admin_new');";
		mysql_query($query4b);
		$refund_admin_tid=mysql_insert_id();
	}
	
	//get last balance of client
	$balance_client=show_txn_client_balance();
	$balance_client_new=$balance_client+$client_charges;
	
	$adm_ref=0;
	$adm_q="select * from $bankapi_child_wallet.realtime where transaction_type='3' and user_id='$uid' and client_order_id='$oid' and service_id='101';";
	$adm_res=mysql_query($adm_q);
	while($adm_rs = mysql_fetch_assoc($adm_res))
	{
		$adm_ref++;
	}
	
	if($adm_ref==0)
	{
		//refund order to client
		$query4b="INSERT INTO $bankapi_child_wallet.realtime (wallet_date, wallet_time, user_id, request_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) VALUES ('$datetime_date', '$datetime_time', '$uid', '0', '101', '$oid', '0', '3', '$filled_remarks', '$balance_client', '$client_charges', '0.00', '$balance_client_new');";
		mysql_query($query4b);
		$refund_client_tid=mysql_insert_id();
	}
	
	//get last balance of retailer
	$balance_retailer=show_txn_user_balance($uid);
	$balance_retailer_new=$balance_retailer+$retailer_charges;
	
	$ret_ref=0;
	$ret_q="select * from $bankapi_child_wallet.distribution where transaction_type='7' and user_id='$uid' and order_id='$oid' and service_id='101' and tid='$mid';";
	$ret_res=mysql_query($ret_q);
	while($ret_rs = mysql_fetch_assoc($ret_res))
	{
		$ret_ref++;
	}
	
	if($ret_ref==0)
	{
		//refund order to retailer
		$query4b="INSERT INTO $bankapi_child_wallet.distribution (wallet_date, wallet_time, user_id, user_id2, request_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) VALUES ('$datetime_date', '$datetime_time', '$uid', '0', '0', '101', '$oid', '$mid', '7', '$filled_remarks', '$balance_retailer', '$retailer_charges', '0.00', '$balance_retailer_new', '$filled_remarks at $datetime_datetime');";
		mysql_query($query4b);
		$refund_retailer_tid=mysql_insert_id();
		update_user_balance($uid);
	}

	// update order status to refunded for admin
	$qry1="update $bankapi_parent_txn.txn_mt set mmt_status='5', refund_source_tid='$refund_source_tid', refund_admin_tid='$refund_admin_tid', refund_client_tid='$refund_client_tid', refund_retailer_tid='$refund_retailer_tid', updated_on='$datetime_datetime' where mmt_id='$mid'";
	mysql_query($qry1);	
	// update order status to refunded for client
	$qry2="update $bankapi_child_txn.txn_mt_child set order_status='5', refund_source_tid='$refund_source_tid', refund_admin_tid='$refund_admin_tid', refund_client_tid='$refund_client_tid', refund_retailer_tid='$refund_retailer_tid', updated_on='$datetime_datetime' where order_id='$oid'";
	mysql_query($qry2);	
}
?>